### ISSUE TITLE
Using packaged tachyons css seems not to work 

### ISSUE THREAD

**Issue by joshy** [octref/vscode-tachyons#1]
Hi, 

thanks for the extension. I am using VSCode (Version 1.7.1) on a Mac and when I point to a CSS name it doesn't work, neither "Peek Definition" nor "Go to Definition". It is a Python Webapp so there is no node_modules, but IIRC it should use the packaged tachyons css.

**Comment by octref** [comment]
Can you post a screenshot of it not working?
Also, can you do Help -> Toggle Developer Tools and paste any errors you see here?

**Comment by joshy** [comment]
The are no errors in the Developer Tools Console. If you can send me how to run only this extension in debug mode, I will try it to debug it my self. The screenshot does not show something meaningful, it just happens nothing.

![screen shot 2016-11-22 at 15 58 35](https://cloud.githubusercontent.com/assets/170219/20528484/a2fc69dc-b0cc-11e6-94cc-22d20d749539.png)

**Comment by octref** [comment]
It's actually not working for me either in 1.7. Likely in the last Code update they changed something. Was using 1.6 and it worked fine.

I'll take a look at it after work. Thanks for your report!

**Comment by octref** [comment]
Published 0.2, should resolve your problem. Give it a try :D

**Comment by joshy** [comment]
Thanks, working now with 0.2.
