### ISSUE TITLE
Does this module still work ?

### ISSUE THREAD

**Issue by abumalick** [octref/vscode-tachyons#3]
It doesn't do anything on my editor, I installed tachyons with in node_modules and use vscode 1.10.1

**Comment by octref** [comment]
Probably not -- I have been busy doing other stuff and haven't updated for a while. I'll take a look this weekend.

**Comment by abumalick** [comment]
Yes it still works sorry, it is because I am using JSX, in an html file it work directly.
Can we mak it work when working in .js file using JSX ?
The code is like that for example:
```
<div className="mw3 tc center">{this.props.icon}</div>
 <div className="mt4 ">{this.props.main}</div>
```

**Comment by abumalick** [comment]
Tryied with this but it don't seem to work ?

`vscode.languages.registerDefinitionProvider('js', provider);`

Can you help me @octref ?

thanks

**Comment by abumalick** [comment]
Yes, this works !
`vscode.languages.registerDefinitionProvider('javascript', provider);`

**Comment by octref** [comment]
I'm building a general solution to that use-case.

This extension just parses tachyon's CSS and provides definition, i.e. going to / peek definition.
However, with that information, it's also possible to do IntelliSense.

For example,
`<div class="mw|` prompts `mw1` to `mw6`.

So not only tachyons, this can support bootstrap, semantic, and other CSS frameworks too.

It's in a private repo and I'm looking forward to having it April.
I'm bringing it to my vue extension first: https://github.com/octref/vetur
But after that I'll try to support React (jsx/tsx) as well.

**Comment by octref** [comment]
Glad you resolved it yourself. Do you want to make a PR 😉 ?

**Comment by abumalick** [comment]
Yep, I will do asap,
it is simple:
`vscode.languages.registerDefinitionProvider(['html', 'javascript'], provider);`

**Comment by octref** [comment]
Yeah, and I don't want to steal your credit 🥇

**Comment by abumalick** [comment]
The credits are already yours, you made the extension.

**Comment by abumalick** [comment]
I am going to bed, see you.

Thank you very much for your extension  :rocket:, I am really bored of searching tachyon website

**Comment by octref** [comment]
> bored of searching tachyon website

Same XD. Good night.

**Comment by rpellerin** [comment]
Sorry for commenting on a closed issue but this doesn't work for me. I have the latest versions of VS-Code and your extension.
In my .js files, when right clicking on class names, `Go to Definition` and `Peek Definition` give me `No definition found for XYZ`.

Example with the following piece of code:

```javascript
const Div = ({ children }) => (
  <div className="tr pa2 absolute right-0 bottom-0 left-0 bg-black-40 white">
    {children}
  </div>
)
```

Am I supposed to edit the settings of VS Code?
Thanks!

**Comment by abumalick** [comment]
Try to install tachyons npm package if you didn't, it may be the problem.
It worked for me in the past but after that it was instable, I don't know
why.
It dont work if your classes are inside quotes like this: `
