### ISSUE TITLE
TSX/JSX support

### ISSUE THREAD

**Issue by philipstanislaus** [octref/vscode-tachyons#5]
Thanks for this plugin, it sounds awesome!

I tried to apply this idea: https://github.com/octref/vscode-tachyons/issues/3 to a fork to get this plugin running with `vscode.languages.registerDefinitionProvider(['html', 'javascript', 'typescript'], provider);`, with no success so far.

Do you have an idea why it fails? 

Many thanks!

**Comment by octref** [comment]
Any errors in the dev console?

**Comment by philipstanislaus** [comment]
@octref thanks for your quick response. 

Nothing relevant, I think: 
<img width="1044" alt="bildschirmfoto 2018-02-01 um 16 58 44" src="https://user-images.githubusercontent.com/6912756/35688326-3b7f318e-0771-11e8-8181-d9c088459ba0.png">

I just tried it again – it works fine in `.html` files, but not in `.js`, `.jsx` or `.tsx` files. 

# Works in .html files
![bildschirmfoto 2018-02-01 um 16 53 34](https://user-images.githubusercontent.com/6912756/35688387-5a84682e-0771-11e8-8721-5798334536bc.png)

# Does not work in .js files
![bildschirmfoto 2018-02-01 um 16 53 57](https://user-images.githubusercontent.com/6912756/35688419-6dbc5f32-0771-11e8-8ac3-5ddea36d79ae.png)

# Does not work in .jsx files
![bildschirmfoto 2018-02-01 um 16 54 22](https://user-images.githubusercontent.com/6912756/35688437-789ef0ae-0771-11e8-9a5c-9feb77dbe106.png)

# Does not work in .tsx files
![bildschirmfoto 2018-02-01 um 16 54 57](https://user-images.githubusercontent.com/6912756/35688448-7d4af206-0771-11e8-8dc5-a92dda4eae0b.png)

**Comment by plievone** [comment]
@philipstanislaus In addition to your changes, have you tried changing extension's [package.json](https://github.com/octref/vscode-tachyons/blob/master/package.json) from
```json
  "activationEvents": [
    "onLanguage:html"
  ],
```
to
```json
  "activationEvents": [
    "onLanguage:html"
    "onLanguage:javascript",
    "onLanguage:javascriptreact",
    "onLanguage:typescript",
    "onLanguage:typescriptreact"
  ],
```
There could be some other activationEvents too, so that all use cases are supported.
If you can make it work, merging it here and publishing a new version would be splendid.

**Comment by octref** [comment]
No, it won't work with jsx/tsx because nobody knows what `tc` there means. It might be a variable name or function name.

I don't think it's practical to support jsx/tsx because of the large variation in the way people do classes and styling.

**Comment by philipstanislaus** [comment]
@plievone thanks, that solves the problem.

@octref I agree that it might lead to confusion – but at least for me, the value of peeking tachyons class definitions overweighs. VSCode is smart enough to handle known definitions first, here is an example: 

## Peeking a class
<img width="936" alt="bildschirmfoto 2018-03-08 um 08 28 13" src="https://user-images.githubusercontent.com/6912756/37138600-fc740366-22aa-11e8-9fd8-2469a8d91d99.png">

## Peeking a string variable
<img width="927" alt="bildschirmfoto 2018-03-08 um 08 28 41" src="https://user-images.githubusercontent.com/6912756/37138606-03695608-22ab-11e8-9a52-7b58d64b2f6a.png">

## Moving forward
Would it be a solution if we added a setting to enable "experimental JSX/TSX support"?

**Comment by plievone** [comment]
@philipstanislaus Hi, yes exactly, peeking works ok, as multiple definitions are just listed as in your screenshot. I just made the change and installed it locally, and it works perfectly. But note that you also need to change the getWordRangeAtPosition to work with "-" in classnames:
```ts
// @ts-ignore: regexp is optional, but missing in typings
const currWordRange = document.getWordRangeAtPosition(position, /[a-z0-9-]+/);
```

@octref A setting would be perfect. In the meantime I'll use my local installation. Thanks for the extension!

EDIT: simplified the regexp to be even more specific to tachyons class names

**Comment by philipstanislaus** [comment]
@plievone implemented your suggestion and created a PR: #6 

Setting is still missing – what do you thing @octref?

**Comment by plievone** [comment]
@philipstanislaus You can also add the setting by adapting these (may contain errors, haven't tested):
in package.json
```json
"contributes": {
    "configuration": {
        "type": "object",
        "title": "tachyons settings",
        "properties": {
            "tachyons.enableJS": {
                "type": "boolean",
                "default": false,
                "description": "Enables tachyon class name definition peeking also for js/jsx/ts/tsx. Note that it will activate on all matching strings, not just css class names."
            }
        }
    }
}
```

then in src extension activate, register more definition providers depending on config (may need reloading the window if checked in extension initialization, but perhaps better that way than always registering the definition provider and making it noop depending on config)
```ts
const enableJS = vscode.workspace.getConfiguration('tachyons.enableJS');
// if enableJS, switch definitionProviders to a larger list
```
And also needs a readme change to advertise the feature

Potentially a problem that this won't work for python or coffeescript or other host languages people use.

**Comment by philipstanislaus** [comment]
@plievone thanks for your support. I will add these changes as soon as @octref buys into this addition. Thanks!
